version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: "redis:alpine"
    networks:
      - backend
    volumes:
      - redis_data:/data

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

networks:
  backend:
    driver: bridge

volumes:
  redis_data: